### PR TITLE
Use SERF_RPC_ADDR env var, if set

### PR DESCRIPTION
**Pull request by msabramo**
This allows using the `SERF_RPC_ADDR` environment variable, that is already understood by Serf (see https://www.serfdom.io/docs/commands/members.html#_rpc_addr).

Cc: @sudarkoff, @bcoca

### CODE REVIEW

**Comment by msabramo** [comment]
b680ce8 adds support for reading the `SERF_RPC_AUTH` environment variable, documented at https://www.serfdom.io/docs/commands/members.html#_rpc_addr:

> Optional RPC auth token. If the agent is configured to use an auth token, then this must be provided or the agent will refuse the command

**Comment by KushalP** [comment]
First off, thanks for the PR! I didn't know about RPC auth in Serf so adding support for that looks like a great idea.

I'm going to comment on each commit individually so reviewing things your end should be easier. However, I'd rather not merge PRs for functionality that doesn't have tests. If you're unsure how to test the auth behaviour let me know and I'll try to help.

**Comment by KushalP** [comment]
After reviewing this PR, it might be better to concentrate on b680ce8 for now as that's functionality that's currently lacking in the library.

Understanding serf's environment variables isn't so important for serfclient's behaviour right now, however I'm happy to be persuaded if I'm wrong here.

**Comment by msabramo** [comment]
Thanks for the comments! You bring up a good point about environment variables and serfclient being a library, so I will focus on the auth token functionality, cleaning it up and adding tests. 

The use case for the environment variables is that I created an Ansible inventory plugin for Serf that uses serfclient (https://github.com/ansible/ansible/pull/11283) and I wanted to make it configurable. I could add environment variable and/or config file functionality to the plugin, but then I thought maybe it was useful to push it down into serfclient so that all tools built on top of serfclient could get that functionality without duplicating code.

But you make some good points about how it adds env vars to pretty low-level code and changes the API contract a bit. 

A few possible alternatives come to mind:

1. Keep the constructor as-is with no env vars and add some utility function on top like perhaps a class method called `get_client_from_env`. That maintains the current API and keeps that code simple and lets folks bypass the env bar stuff but also lets folks opt into the env var functionality. 

2. Do nothing in serfclient and leave it to a client application or library on top of serfclient. 

For now I'll assume #2 and concentrate on the auth token stuff, but if you're open to #1, let me know.

**Comment by msabramo** [comment]
See #12.

**Comment by KushalP** [comment]
I think adding a class that understands these environment variables could be a good thing.

I've created an issue that better describes it: #16

**Comment by msabramo** [comment]
See #17

**Pull request closed without merging**
